### ISSUE TITLE
에피소드번호가 없는경우

### ISSUE THREAD

**Issue by xswqaz** [hojel/DaumMovie.bundle#10]
n2xml.py로 epg를 끌어오고 있습니다만, 에피번호가 없는경우가 있습니다
파일명에 들어있는 yyyy-mm-dd로 에피를 추측하여 메타데이터를 작성할수 있을까요

**Comment by hojel** [comment]
n2xml.py이 뭔지를 모릅니다만 daum 회차정보에 broadcastDate 란 항목이 있으니 가능하겠죠.
