### ISSUE TITLE
Daum 정보를 또 못 불러 오고 있습니다.

### ISSUE THREAD

**Issue by airbogo** [hojel/DaumMovie.bundle#12]
이것저것 확인 해보고는 있는데 메타정보를 전혀 끌어오지 못하는 현상이 있는데요 저만 그런지 다른분들도 그러신지 모르겠네요 
항상 좋은 프로그램 잘 사용하고 있습니다. 
답변 주시면 감사하겠습니다. ^^

**Comment by VoltIcaRus** [comment]
다음 점점 짜증나네요 왜 계속바꾸는건지....

**Comment by rubyon** [comment]
다음 메타 정보중 예전엔 배우 이름 필드가 actor 였는데 플렉스가 업데이트 되면서 actor 에서 name 으로 바뀐듯 하네요

**Comment by hojel** [comment]
axfree님이 수정하신 걸 업데이트했습니다.
