### ISSUE TITLE
다음이 또 리뉴얼을 한거같습니다..

### ISSUE THREAD

**Issue by VoltIcaRus** [hojel/DaumMovie.bundle#5]
다음이 또 사이트 리뉴얼을 한거같은데
저만 그런줄 알았는데 다른분들도 메타데이터를 못가져오신다고 하더라고요...
확인 가능하신가요?? 뭐 ..기존에도 tv프로그램은 잘못가져오긴했지만요..

**Comment by dongbum** [comment]
방금 테스트 해봤습니다.

기존에 이미 메타데이터 잘 검색되어서 입력되어 있던 영화를 다른 곳으로 뺐다가 다시 넣어봤는데 메타데이터를 못 받아오네요. 다음무비가 리뉴얼 되니 문제가 생기는게 당연하겠네요.. :-)

**Comment by lunarlove** [comment]
저도 계속 검색이 안되길래 daum에 가보니 리뉴얼이 되어 있더군요.
수정된 다음 에이전트가 빨리 올라 오길 고대 하겠습니다. ^^

**Comment by KwangMin1108** [comment]
제가 주소 일부를 수정해서 일단 데이터를 받아오게 고쳤는데, 그래도 아직 동작은 안합니다

..문제는 제가 잘못 눌러서 마스터에 커밋해버렸는데 이거 어떻게 되돌리나요...

...아직 미완성이라 커밋할 일이 아닌데 죄송합니다...

**Comment by KwangMin1108** [comment]
...아 다행이다 이쪽으로 커밋된 건 아니군요 (...........) 헤메어서 다시 죄송합니다 (....)

**Comment by VoltIcaRus** [comment]
동작 확인했습니다 감사합니다

**Comment by VoltIcaRus** [comment]
근데 여전히 tv 제목만가져오는건 여전하네요...

**Comment by axfree** [comment]
문제가 되는 프로그램의 타이틀을 알려주시면 확인해 보겠습니다.

**Comment by VoltIcaRus** [comment]
http://m.movie.daum.net/tv/main?tvProgramId=75936
제목만 가져오고 다른걸 못가져오더라고요 제 나스단의 문제인줄알고 권한설정만져도 뭐 그대로니..

**Comment by axfree** [comment]
확인해 봤는데 일본 애니메이션의 경우는 TV 쪽과는 시스템이 다른 듯 합니다. TV쪽 관련 URL들이 전혀 동작을 안하네요.
웹에서 봐도 화면 구조도 다르고, 특히 회차 정보가 아예 없는게 눈에 띄네요.
이게 이번 리뉴얼과는 관계없이 안되던거죠?
그렇다면 리뉴얼 이슈는 여기서 닫고, 일본 애니쪽 지원 여부는 별도 이슈에서 다뤄보면 어떨까 합니다.

**Comment by VoltIcaRus** [comment]
넵 알겠습니다 확인 감사합니다!
