### ISSUE TITLE
일본 애니메이션 메타데이터 지원에 관하여..

### ISSUE THREAD

**Issue by VoltIcaRus** [hojel/DaumMovie.bundle#8]
DaumMovieTV.bundle 버전이랑 그후 버전까지는 일본 애니메이션의 메타데이터가 잘불러와졌지만
정확히 기억은안나지만 2015년 후반기..부터 2016년부로 일본애니메이션의 메타데이터를 전혀받아오지못하고있습니다 다음쪽이 애니메이션 담당자를 갈갈이했다던가..그냥 애니메이션 정보를 대충 입력하게 방침을 바꿨다든지... 2015년 상반기의 애니메이션은 정상적으로 다 불러옵니다만.(2015상반기이전의 보든 애니메이션 데이터들은 회차정보도 등록되어있고 구조도 같았기에 불러와졌을걸로 생각합니다 )
신작애니메이션쪽들은 대부분 안가져와집니다  다음이 이번 리뉴얼하기전 포크된  axfree님의 번들로 시도한적이
있는데요 그때 한두신작품은 메타데이터를  가져왔습니다
구조자체가 다르다고하네요...다음쪽이 무슨생각으로 일반 tv랑 애니메이션을 다르게 회차정보 등록도 안하고 만든건진 모르겠지만요
 새 애니메이션이 나오면 이제 다음 영화를 찾아서 직접 수동으로 메타데이터를 입력을 하게되네요 ㅎ 이미 회차정보는 포기한지오래네요.. 일일히 다찾아서 등록하다 포기.. 적어도 포스터나 설명 년도 방송사 성우정도는 불러와주었으면하는데 말이죠..
지원이 가능할까요..?
샘플링크
:http://m.movie.daum.net/tv/main?tvProgramId=75936
http://m.movie.daum.net/tv/main?tvProgramId=76022
http://m.movie.daum.net/tv/main?tvProgramId=76265

회차목록이 있는 애니메이션.
http://m.movie.daum.net/tv/main?tvProgramId=66929

**Comment by axfree** [comment]
일본 애니메이션 쪽은 다음에서 입력한 정보가 부실해 보여서 예외처리를 해 가며 작업할 의욕이 생기질 않네요. 제가 애니 쪽에 별 관심이 없기도 하고요 :)
한국어만 살짝 포기하면 thetvdb.com이 괜찮아 보이긴 합니다. 애니쪽 부터라도 이전을 고려해 보심이...

**Comment by hojel** [comment]
저도 daum은 한국드라마/예능 쪽만 추천합니다.
그리고 thetvdb에 직접 한글 에피소드 추가하는 것 또한 추천합니다. daum에 있는 에피소드 내용을 복사하더라도 원래 방송사에서 보도자료로 배포한거라서 저작권이 문제가 될 이유가 없습니다.
